backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "site_content"
    label: "Home_Page"
    files:
      - name: "content"
        label: "Home_Content"
        file: "src/data/content.json"
        fields:
          - { label: "Site Title", name: "title", widget: "string" }
          - { label: "School Name", name: "school_name", widget: "string" }
          - { label: "Logo", name: "logo", widget: "image", required: false }
          - { label: "Secondary Logo", name: "secondary_logo", widget: "image", required: false }
          - { label: "Footer Logo", name: "footer_logo", widget: "image", required: false }
          - { label: "Footer School Name", name: "footer_school_name", widget: "string" }
          
          # Hero Section
          - { label: "Hero Heading", name: "hero_heading", widget: "string" }
          - { label: "Hero Text", name: "hero_text", widget: "text" }
          - { label: "Hero Button Text", name: "hero_button_text", widget: "string" }
          
          # About Section
          - { label: "About Image", name: "about_image", widget: "image", required: false }
          - { label: "About Heading", name: "about_heading", widget: "string" }
          - { label: "About Text", name: "about_text", widget: "markdown" }
          - { label: "Learn More Text", name: "learn_more_text", widget: "string" }
          
          # Vision Section
          - { label: "Vision Image", name: "vision_image", widget: "image", required: false }
          - { label: "Vision Heading", name: "vision_heading", widget: "string" }
          - { label: "Vision Text", name: "vision_text", widget: "markdown" }
          - { label: "Donate Button Text", name: "donate_button_text", widget: "string" }
          
          # Headteacher Section
          - { label: "Headteacher Heading", name: "headteacher_heading", widget: "string" }
          - { label: "Headteacher Message", name: "headteacher_message", widget: "text" }
          
          # Visit Section
          - { label: "Visit Heading", name: "visit_heading", widget: "string" }
          - { label: "Visit Text", name: "visit_text", widget: "text" }
          - { label: "Visit Text Continued", name: "visit_text_continued", widget: "text" }
          - { label: "Visit Button Text", name: "visit_button_text", widget: "string" }
          
          # Ethos Section
          - { label: "Ethos Heading", name: "ethos_heading", widget: "string" }
          - { label: "Ethos Text", name: "ethos_text", widget: "text" }
          - { label: "Ethos Text Continued", name: "ethos_text_continued", widget: "text" }
          - { label: "Ethos Text Conclusion", name: "ethos_text_conclusion", widget: "text" }
          - { label: "Ethos Image", name: "ethos_image", widget: "image", required: false }
          - { label: "Read More Text", name: "read_more_text", widget: "string" }
          
          # Programs Section
          - label: "Join Heading"
            name: "join_heading"
            widget: "string"
          - label: "Thematic Heading"
            name: "thematic_heading"
            widget: "string"
          - label: "Programs"
            name: "programs"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Description", name: "description", widget: "text" }
          
          # Alternate Sections
          - label: "Academic Section"
            name: "academic"
            widget: "object"
            fields:
              - { label: "Heading", name: "heading", widget: "string" }
              - { label: "Text", name: "text", widget: "text" }
              - { label: "Image", name: "image", widget: "image", required: false }
          
          - label: "Happy Section"
            name: "happy"
            widget: "object"
            fields:
              - { label: "Heading", name: "heading", widget: "string" }
              - { label: "Text", name: "text", widget: "text" }
              - { label: "Image", name: "image", widget: "image", required: false }
          
          - { label: "Read More Button Text", name: "read_more_button", widget: "string" }
          
          # Counter Section
          - { label: "Student Count", name: "student_count", widget: "number" }
          - { label: "Student Label", name: "student_label", widget: "string" }
          - { label: "Alumni Count", name: "alumni_count", widget: "number" }
          - { label: "Alumni Label", name: "alumni_label", widget: "string" }
          - { label: "Activities Count", name: "activities_count", widget: "number" }
          - { label: "Activities Label", name: "activities_label", widget: "string" }
          
          # Footer
          - { label: "Footer Tagline", name: "footer_tagline", widget: "text" }
          
          - label: "Social Links"
            name: "social_links"
            widget: "list"
            fields:
              - { label: "Platform", name: "platform", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }
          
          - label: "Footer Links"
            name: "footer_links"
            widget: "list"
            fields:
              - { label: "Text", name: "text", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }
          
          - { label: "Contact Heading", name: "contact_heading", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Phone 1", name: "phone1", widget: "string" }
          - { label: "Phone 2", name: "phone2", widget: "string" }
          - { label: "Address", name: "address", widget: "string" }
          
          - { label: "Copyright Text", name: "copyright_text", widget: "string" }
          - { label: "Designer Text", name: "designer_text", widget: "string" }
          - { label: "Designer Link", name: "designer_link", widget: "string" }
          - { label: "Designer Name", name: "designer_name", widget: "string" }
          - { label: "Admin Text", name: "admin_text", widget: "string" }
          
          # Slideshow Images
          - label: "Slideshow Images"
            name: "slideshow_images"
            widget: "list"
            fields:
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Alt Text", name: "alt", widget: "string" }

  - name: "about_content"
    label: "About Page Content"
    files:
      - name: "about"
        label: "About Page"
        file: "src/data/about.json"
        fields:
          - { label: "About Page Title", name: "about_page_title", widget: "string" }
          - { label: "Hero Title", name: "about_hero_title", widget: "string" }
          
          # Mission/Aim Section
          - { label: "Aim Heading", name: "aim_heading", widget: "string" }
          - { label: "Aim Text 1", name: "aim_text_1", widget: "text" }
          - { label: "Aim Text 2", name: "aim_text_2", widget: "text" }
          - { label: "Mission Image", name: "mission_image", widget: "image" }
          
          # About Section
          - { label: "About Heading", name: "about_heading", widget: "string" }
          - { label: "About Text 1", name: "about_text_1", widget: "text" }
          - { label: "About Text 2", name: "about_text_2", widget: "text" }
          - { label: "About Text 3", name: "about_text_3", widget: "text" }
          - { label: "About Section Image", name: "about_section_image", widget: "image" }
          
          # Mission/Vision/Values Section
          - { label: "Mission Heading", name: "mission_heading", widget: "string" }
          - { label: "Mission Text", name: "mission_text", widget: "text" }
          - { label: "Vision Heading", name: "vision_heading", widget: "string" }
          - { label: "Vision Text", name: "vision_text", widget: "text" }
          - { label: "Values Heading", name: "values_heading", widget: "string" }
          - { label: "Values Text", name: "values_text", widget: "text" }
          
          # Team Section
          - { label: "Team Heading", name: "team_heading", widget: "string" }
          - { label: "Team Subheading", name: "team_subheading", widget: "text" }
          - label: "Team Members"
            name: "team_members"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Position", name: "position", widget: "string" }
              - { label: "Image", name: "image", widget: "image" }
          
          # Empower Section
          - { label: "Empower Heading", name: "empower_heading", widget: "string" }
          - { label: "Empower Text 1", name: "empower_text_1", widget: "text" }
          - { label: "Empower Text 2", name: "empower_text_2", widget: "text" }
          - { label: "Empower Image", name: "empower_image", widget: "image" }
          
          # Life at School Section
          - { label: "Life Heading", name: "life_heading", widget: "string" }
          - { label: "Life Text 1", name: "life_text_1", widget: "text" }
          - { label: "Life Text 2", name: "life_text_2", widget: "text" }
          - { label: "Life Text 3", name: "life_text_3", widget: "text" }
          
          # Gallery
          - label: "Gallery Images"
            name: "gallery_images"
            widget: "list"
            fields:
              - { label: "Image", name: "url", widget: "image" }
              - { label: "Alt Text", name: "alt", widget: "string", required: false }
          
          # Footer
          - { label: "Footer Logo", name: "footer_logo_about", widget: "image" }
          - { label: "Footer School Name", name: "footer_school_name_about", widget: "string" }
          - { label: "Footer Tagline", name: "footer_tagline_about", widget: "text" }
          
          - label: "Social Links"
            name: "social_links_about"
            widget: "list"
            fields:
              - { label: "Platform", name: "platform", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }
          
          - label: "Footer Links"
            name: "footer_links_about"
            widget: "list"
            fields:
              - { label: "Text", name: "text", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }
          
          - { label: "Contact Heading", name: "contact_heading_about", widget: "string" }
          - { label: "Email", name: "email_about", widget: "string" }
          - { label: "Phone 1", name: "phone1_about", widget: "string" }
          - { label: "Phone 2", name: "phone2_about", widget: "string" }
          - { label: "Address", name: "address_about", widget: "string" }
          
          - { label: "Copyright Text", name: "copyright_text_about", widget: "string" }
          - { label: "Designer Text", name: "designer_text_about", widget: "string" }
          - { label: "Designer Link", name: "designer_link_about", widget: "string" }
          - { label: "Designer Name", name: "designer_name_about", widget: "string" }
          - { label: "Admin Text", name: "admin_text_about", widget: "string" }

  - name: "projects_content"
    label: "Projects Page Content"
    files:
      - name: "projects"
        label: "Projects Page"
        file: "src/data/projects.json"
        fields:
          - { label: "Page Title", name: "title", widget: "string" }
          - { label: "School Name", name: "school_name", widget: "string" }
          - { label: "Logo", name: "logo", widget: "image", required: false }
          - { label: "Footer Logo", name: "footer_logo", widget: "image", required: false }
          - { label: "Footer School Name", name: "footer_school_name", widget: "string" }
          - { label: "Admin Text", name: "admin_text", widget: "string" }
          
          # Parallax Section
          - { label: "Parallax Title", name: "parallax_title", widget: "string" }
          
          # Projects Header
          - { label: "Projects Heading", name: "projects_heading", widget: "string" }
          - { label: "Projects Subheading", name: "projects_subheading", widget: "text" }
          
          # Projects
          - label: "Projects"
            name: "projects"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Description", name: "description", widget: "markdown" }
              - label: "Achievements"
                name: "achievements"
                widget: "list"
                required: false
                fields:
                  - { label: "Achievement", name: "item", widget: "string" }
              - { label: "Appreciation Text", name: "appreciation", widget: "text", required: false }
          
          # Footer
          - { label: "Footer Tagline", name: "footer_tagline_projects", widget: "text" }
          
          - label: "Social Links"
            name: "social_links_projects"
            widget: "list"
            fields:
              - { label: "Platform", name: "platform", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }
          
          - label: "Footer Links"
            name: "footer_links_projects"
            widget: "list"
            fields:
              - { label: "Text", name: "text", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }
          
          - { label: "Contact Heading", name: "contact_heading_projects", widget: "string" }
          - { label: "Email", name: "email_projects", widget: "string" }
          - { label: "Phone 1", name: "phone1_projects", widget: "string" }
          - { label: "Phone 2", name: "phone2_projects", widget: "string" }
          - { label: "Address", name: "address_projects", widget: "string" }
          
          - { label: "Copyright Text", name: "copyright_text_projects", widget: "string" }
          - { label: "Designer Text", name: "designer_text_projects", widget: "string" }
          - { label: "Designer Link", name: "designer_link_projects", widget: "string" }
          - { label: "Designer Name", name: "designer_name_projects", widget: "string" }

  - name: "contacts_content"
    label: "Contact Page Content"
    files:
      - name: "contacts"
        label: "Contact Page"
        file: "src/data/contacts.json"
        fields:
          - { label: "Page Title", name: "title_contact", widget: "string" }
          - { label: "School Name", name: "school_name_contact", widget: "string" }
          - { label: "Logo", name: "logo_contact", widget: "image", required: false }
          - { label: "Footer Logo", name: "footer_logo_contact", widget: "image", required: false }
          - { label: "Footer School Name", name: "footer_school_name_contact", widget: "string" }
          - { label: "Admin Text", name: "admin_text_contact", widget: "string" }
          
          # Contact Page Header
          - { label: "Contact Page Heading", name: "contact_page_heading", widget: "string" }
          - { label: "Contact Page Subheading", name: "contact_page_subheading", widget: "text" }
          
          # Contact Information
          - { label: "Contact Section Heading", name: "contact_section_heading", widget: "string" }
          - { label: "Office Address", name: "office_address", widget: "string" }
          - { label: "Phone 1", name: "phone1_contact", widget: "string" }
          - { label: "Phone 2", name: "phone2_contact", widget: "string" }
          - { label: "Email", name: "email_contact", widget: "string" }
          - { label: "Working Hours", name: "working_hours", widget: "string" }
          
          # Map Section
          - { label: "Map Heading", name: "map_heading", widget: "string" }
          - { label: "Google Maps Embed URL", name: "google_maps_url", widget: "string" }
          
          # Form Section
          - { label: "Form Heading", name: "form_heading", widget: "string" }
          
          # Footer
          - { label: "Footer Tagline", name: "footer_tagline_contact", widget: "text" }
          
          - label: "Social Links"
            name: "social_links_contact"
            widget: "list"
            fields:
              - { label: "Platform", name: "platform", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }
          
          - label: "Footer Links"
            name: "footer_links_contact"
            widget: "list"
            fields:
              - { label: "Text", name: "text", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }
          
          - { label: "Contact Heading", name: "contact_heading_contact", widget: "string" }
          - { label: "Email", name: "email_footer_contact", widget: "string" }
          - { label: "Phone 1", name: "phone1_footer_contact", widget: "string" }
          - { label: "Phone 2", name: "phone2_footer_contact", widget: "string" }
          - { label: "Address", name: "address_contact", widget: "string" }
          
          - { label: "Copyright Text", name: "copyright_text_contact", widget: "string" }
          - { label: "Designer Text", name: "designer_text_contact", widget: "string" }
          - { label: "Designer Link", name: "designer_link_contact", widget: "string" }
          - { label: "Designer Name", name: "designer_name_contact", widget: "string" }
