backend:
  name: git-gateway
  branch: main # Change this if you're using a different branch

media_folder: "static/uploads" # Where images will be stored
public_folder: "/uploads"

collections:
  - name: "blog" # Identifier
    label: "Blog Posts" # Admin Panel Display Name
    folder: "content/blog" # Path to store posts
    create: true # Allow creating new posts
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image" }
