backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "content"
    label: "Content"
    files:
      - name: "site_content"
        label: "Site Content"
        file: "src/data/content.json"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Hero Heading", name: "hero_heading", widget: "string" }
          - { label: "Hero Text", name: "hero_text", widget: "text" }
          - { label: "Hero Button Text", name: "hero_button_text", widget: "string" }
          - { label: "About Heading", name: "about_heading", widget: "string" }
          - { label: "About Text", name: "about_text", widget: "markdown" }
          - { label: "Vision Text", name: "vision_text", widget: "markdown" }
