backend:
  name: github
  repo: Dariusmumbere/signalpreparatory
  branch: main

media_folder: "assets/uploads"  # Where uploaded images will go
public_folder: "/assets/uploads"

collections:
  - name: "announcements"
    label: "Announcements"
    folder: "content/announcements"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
