backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Home Page"
        file: "index.html"
        format: html
        frontmatter_delimiter: ["---", "---"]
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Hero Heading", name: "hero_heading", widget: "string" }
          - { label: "Hero Text", name: "hero_text", widget: "text" }
          - { label: "Hero Button Text", name: "hero_button_text", widget: "string" }
          - { label: "About Heading", name: "about_heading", widget: "string" }
          - { label: "About Text", name: "about_text", widget: "markdown" }
          - { label: "Vision Text", name: "vision_text", widget: "markdown" }

  - name: "settings"
    label: "Settings"
    files:
      - name: "general"
        label: "General Settings"
        file: "admin/config.yml"
        fields:
          - { label: "Site Title", name: "site_title", widget: "string" }
          - { label: "Site Description", name: "site_description", widget: "text" }

publish_mode: editorial_workflow

slug:
  encoding: "unicode"
  clean_accents: true
  sanitize_replacement: "-"

show_preview_links: true

editor:
  preview: true
