backend:
  name: git-gateway
  branch: main  # Your default branch (main/master)

media_folder: "images/uploads"  # Where uploaded images go
public_folder: "/images/uploads"  # Public path for images

collections:
  # Example: Home Page (editable via CMS)
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Home Page"
        file: "index.html"  # Path to your HTML file
        fields:
          - { label: "Hero Title", name: "hero_title", widget: "string" }
          - { label: "Hero Subtitle", name: "hero_subtitle", widget: "text" }
          - { label: "About Section", name: "about_text", widget: "markdown" }
          - { label: "Featured Image", name: "hero_image", widget: "image" }

  # Example: Blog Posts
  - name: "blog"
    label: "Blog"
    folder: "_posts/blog"  # Creates new markdown files here
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
